apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-app
spec:
  replicas: {{ .Values.app.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: otus-app
  template:
    metadata:
      labels:
        app: otus-app
        {{- include "otus-app.selectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      initContainers:
        - name: wait-for-db
          image: postgres:13-alpine
          command: ['sh', '-c',
                    'until pg_isready -h otus-app-postgresql -U postgres; do sleep 2; done']
          envFrom:
            - secretRef:
                name: db-secret
      containers:
        - name: otus-app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
            - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
              value: "true"
          envFrom:
            - secretRef:
                name: db-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path | quote }}
              port: 8000
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path | quote }}
              port: 8000
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
            - name: http
              containerPort: 8000
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: app-config