{{- if .Values.app.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-app-ingress
spec:
  ingressClassName: {{ .Values.app.ingress.className | quote }}
  rules:
    - host: {{ .Values.app.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.app.ingress.paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: otus-app-service
                port:
                  number: {{ $.Values.app.service.port }}
          {{- end }}
{{- end }}