apiVersion: batch/v1
kind: Job
metadata:
  name: otus-app-db-check
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: check
          image: postgres:13-alpine
          command: ['sh', '-c', 'pg_isready -h otus-app-postgresql -U postgres']
          envFrom:
            - secretRef:
                name: db-secret