apiVersion: v1
kind: Service
metadata:
  name: otus-app-service
  namespace: {{ .Values.global.namespace | quote }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: otus-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}