apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: m
data:
  application.yml: |
    server:
      port: 8000
    spring:
      datasource:
        url: jdbc:postgresql://postgres-postgresql:5432/otus
      jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            jdbc:
              lob:
                non_contextual_creation: true
    logging:
      level:
        root: DEBUG
        org.hibernate.SQL: INFO
        org.hibernate.type: INFO