apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-app-ingress
  namespace: m
spec:
  ingressClassName: nginx
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix  # Все пути, начинающиеся с /api/v1/
            backend:
              service:
                name: otus-app-service
                port:
                  number: 80
          - path: /health
            pathType: Exact  # Точное совпадение
            backend:
              service:
                name: otus-app-service
                port:
                  number: 80